"""empty message

Revision ID: 9d6da7022826
Revises: 55fdb9022b60
Create Date: 2020-02-24 20:51:21.713069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d6da7022826'
down_revision = '55fdb9022b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipped_date', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'shippid_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shippid_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'shipped_date')
    # ### end Alembic commands ###
